### ISSUE TITLE
Add a credits scene with links to the assets found in README.

### ISSUE THREAD

**Issue by silwalanish** [silwalanish/minecraft2d#13]
- Add a credit scene that can be accessed from main menu.
- Add links to the following assets in the `CreditScene`:
    1. Ground Textures: https://opengameart.org/content/2d-minecraft-sprite-pack
    2. Steve Textures: https://opengameart.org/content/2d-minecraft-steve
    3. Zombie Sprite: https://opengameart.org/content/zombie-character-sprite
- Add a back button that goes back to main menu

**Comment by trblackw** [comment]
Would this credits view be visible after the "Game Over" screen?

**Comment by silwalanish** [comment]
@trblackw you could add a button in the `GameEndScene` that shows the credits. But it's optional, for now.

**Comment by silwalanish** [comment]
Fixed by #15
