### ISSUE TITLE
Add a help scene with controls info.

### ISSUE THREAD

**Issue by silwalanish** [silwalanish/minecraft2d#14]
- Add a help scene that can be from main menu.
- Add controls information on the help scene.
- Add rules

# Controls
`Up Arrow | W` => Jump
`Left Arrow | A` => Move left
`Right Arrow | D` => Move Right
`B` => Toggle Build/Mine mode
`E` => Eat food(apple)
`1-8` => Change ground to be built in building mode. Also can be changed by clicking on the icons on the left.

# Rules
- Can't eat food unless hunger(BLUE) bar is less than 50.
- Eating food restores health and hunger by 50 with maximum being 100 for both.
- When Build Mode is on clicking on empty space creates the selected ground.
- When Mine Mode is on clicking on ground/trees with in 1 block of player will be mined.
- Mining resources gives rewards.
- Zombies will follow when near
- If Zombies touch then health decrease.
- When hunger becomes zero health decreases.
- When health becomes zero player dies.
- Building ground requires resources.
- In creative mode, any ground can be removed and added without charge.

**Comment by vspedr** [comment]
Hi, I'd like to give it a try!

**Comment by silwalanish** [comment]
> Hi, I'd like to give it a try!

Sure.
