### ISSUE TITLE
Add preview of the game assets in README under Assets heading

### ISSUE THREAD

**Issue by silwalanish** [silwalanish/minecraft2d#3]
- Add preview of the game assets such as:
    1. Steve
    2. Zombie
    3. Stone Textures
    4. Grass Textures
    5. Mud Textures
    6. so on

**Note: Make preview of size 50x50**

## Use the following format.
```
<div>
    <img src="[relative-path-to-asset]?raw=true" width=50 height=50>
    <img src="[relative-path-to-asset]?raw=true" width=50 height=50>
</div>
```

### Example:
<div>
    <img src="https://github.com/silwalanish/minecraft2d/blob/master/images/minecraft/grass.png?raw=true" width=50 height=50>
    <img src="https://github.com/silwalanish/minecraft2d/blob/master/images/minecraft/stone.png?raw=true" width=50 height=50>
</div>

**Comment by HencoSmith** [comment]
Working on it 👍
