### ISSUE TITLE
Add public copyright license

### ISSUE THREAD

**Issue by silwalanish** [silwalanish/minecraft2d#5]
- Add public copyright license for the project as LICENSE.txt
- Add license text for each source code file. (Use a plugin, maybe?)

**Comment by rohitjmathew** [comment]
@silwalanish have attached a PR with the needed MIT license. This should cover this scenario.

**Comment by rohitjmathew** [comment]
@silwalanish you don't need to add the license above each file. The license means that everything under this repo comes under the terms of the license. 

Hence, I suggest you remove it from all the files and maintain just the one license file
